# Generated by Django 4.1.3 on 2023-06-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_alter_longtoshort_user_id_alter_userprofile_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtoshort',
            name='custom_name',
            field=models.CharField(max_length=50),
        ),
    ]
